/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author WIN10
 */
public class formPilihManager extends javax.swing.JFrame {

    /**
     * Creates new form formPilihManager
     */
    int jabatan;
    public formPilihManager(int Jabatan) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        this.jabatan = jabatan;
        System.out.println(jabatan);
    }

    private formPilihManager() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnStok1 = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnStok = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistory.setBackground(new java.awt.Color(255, 255, 255));
        btnHistory.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonManager.png"))); // NOI18N
        btnHistory.setText("Master History");
        btnHistory.setBorder(null);
        btnHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
        });
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 110, 50));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu Manager");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, 380, 60));

        btnBack1.setBackground(new java.awt.Color(24, 90, 102));
        btnBack1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Back(3).png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnStok1.setBackground(new java.awt.Color(255, 255, 255));
        btnStok1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnStok1.setForeground(new java.awt.Color(0, 0, 0));
        btnStok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonManager.png"))); // NOI18N
        btnStok1.setText("Master Voucher");
        btnStok1.setBorder(null);
        btnStok1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStok1MouseClicked(evt);
            }
        });
        btnStok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStok1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnStok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 50));

        btnKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        btnKaryawan.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(0, 0, 0));
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonKary.png"))); // NOI18N
        btnKaryawan.setText("Master Karyawan");
        btnKaryawan.setBorder(null);
        btnKaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseClicked(evt);
            }
        });
        getContentPane().add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 130, 50));

        btnStok.setBackground(new java.awt.Color(255, 255, 255));
        btnStok.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnStok.setForeground(new java.awt.Color(0, 0, 0));
        btnStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonManager.png"))); // NOI18N
        btnStok.setText("Master Stok");
        btnStok.setBorder(null);
        btnStok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStokMouseClicked(evt);
            }
        });
        getContentPane().add(btnStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/MasterKasir.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 390, -1));

        jButton1.setBackground(new java.awt.Color(24, 90, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/minimize(2).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(24, 90, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Exit (3).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Header.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/bgKasir.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setDoubleBuffered(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        MasterHistory f = new MasterHistory(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void btnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseClicked
        MasterKaryawan f = new MasterKaryawan(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKaryawanMouseClicked

    private void btnStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStokMouseClicked
        MasterStok f = new MasterStok(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStokMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(formPilihManager.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnStok1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStok1MouseClicked
        // TODO add your handling code here:
        Voucher f = new Voucher(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStok1MouseClicked

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        LoginForm f = new LoginForm();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnStok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStok1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPilihManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPilihManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPilihManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPilihManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPilihManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnStok1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
