/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author WIN10
 */
public class formPilihKasir extends javax.swing.JFrame {

    /**
     * Creates new form formPilihKasir
     */
    int jabatan;
    public formPilihKasir(int jabatan) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        this.jabatan = jabatan;
    }

    private formPilihKasir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        btnVoucher = new javax.swing.JButton();
        btnKasir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setBackground(new java.awt.Color(24, 90, 102));
        btnBack1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Back(3).png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnVoucher.setBackground(new java.awt.Color(255, 255, 255));
        btnVoucher.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        btnVoucher.setForeground(new java.awt.Color(0, 0, 0));
        btnVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonKasir.png"))); // NOI18N
        btnVoucher.setText("Voucher");
        btnVoucher.setBorder(null);
        btnVoucher.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 130, 70));

        btnKasir.setBackground(new java.awt.Color(255, 255, 255));
        btnKasir.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        btnKasir.setForeground(new java.awt.Color(0, 0, 0));
        btnKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonKasir.png"))); // NOI18N
        btnKasir.setText("Kasir");
        btnKasir.setBorder(null);
        btnKasir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKasirMouseClicked(evt);
            }
        });
        getContentPane().add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, 70));

        jButton1.setBackground(new java.awt.Color(24, 90, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/minimize(2).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 30, 30));

        jButton2.setBackground(new java.awt.Color(24, 90, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Exit (3).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu kasir");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, 290, 60));

        btnHistory.setBackground(new java.awt.Color(255, 255, 255));
        btnHistory.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(0, 0, 0));
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/buttonKasir.png"))); // NOI18N
        btnHistory.setText("History");
        btnHistory.setBorder(null);
        btnHistory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
        });
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/masterManager.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 390, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Header.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/bgKasir.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setDoubleBuffered(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMouseClicked
        MasterKasir f = new MasterKasir(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKasirMouseClicked

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        MasterHistory f = new MasterHistory(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(formPilihKasir.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        // TODO add your handling code here:
        Voucher f = new Voucher(jabatan);
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
         LoginForm f = new LoginForm();
            f.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPilihKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPilihKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPilihKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPilihKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPilihKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnKasir;
    private javax.swing.JButton btnVoucher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
