/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class MasterKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form MasterKaryawan
     */
    int jabatan;
    Object[] rows;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    PreparedStatement pr;
    public MasterKaryawan(int jabatan) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        this.jabatan = jabatan;
        TabelKaryawan.setDefaultEditor(Object.class, null);
        rows = new Object[]{"ID Karyawan","Username","Nama","Email","Alamat","Nomor Telepon","Jabatan","Status"};
        model = new DefaultTableModel(rows,0);
        TabelKaryawan.setModel(model);
        Tampil();
        TabelKaryawan.getTableHeader().setReorderingAllowed(false);



        
    }

    private MasterKaryawan() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        ButtonOFF = new javax.swing.JButton();
        cmbJabatan = new javax.swing.JComboBox<>();
        tbCari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tbNoTelp = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        tbEmail = new javax.swing.JTextField();
        ButtonUpdate = new javax.swing.JButton();
        tbAlamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnAktif = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelKaryawan = new javax.swing.JTable();
        cmbPilih = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 760, 490, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 860, 490, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 810, 490, -1));

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/searchBlc(1).png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 30, 30));

        btnInsert.setBackground(new java.awt.Color(204, 204, 204));
        btnInsert.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(0, 0, 0));
        btnInsert.setText("Insert");
        btnInsert.setBorder(null);
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 139, 48));

        ButtonOFF.setBackground(new java.awt.Color(204, 204, 204));
        ButtonOFF.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        ButtonOFF.setForeground(new java.awt.Color(0, 0, 0));
        ButtonOFF.setText("OFF");
        ButtonOFF.setBorder(null);
        ButtonOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonOFFMouseClicked(evt);
            }
        });
        getContentPane().add(ButtonOFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 770, 139, 48));

        cmbJabatan.setBackground(new java.awt.Color(187, 187, 187));
        cmbJabatan.setForeground(new java.awt.Color(0, 0, 0));
        cmbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "KASIR", "ADMIN", "SEMUA" }));
        cmbJabatan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJabatanItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 180, 30));

        tbCari.setBackground(new java.awt.Color(204, 204, 204));
        tbCari.setBorder(null);
        tbCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbCariKeyTyped(evt);
            }
        });
        getContentPane().add(tbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 300, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 490, -1));

        tbNoTelp.setBackground(new java.awt.Color(255, 255, 255));
        tbNoTelp.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        tbNoTelp.setForeground(new java.awt.Color(0, 0, 0));
        tbNoTelp.setBorder(null);
        getContentPane().add(tbNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 820, 480, 39));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 490, -1));

        tbEmail.setBackground(new java.awt.Color(255, 255, 255));
        tbEmail.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        tbEmail.setForeground(new java.awt.Color(0, 0, 0));
        tbEmail.setBorder(null);
        getContentPane().add(tbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 720, 480, 39));

        ButtonUpdate.setBackground(new java.awt.Color(204, 204, 204));
        ButtonUpdate.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        ButtonUpdate.setForeground(new java.awt.Color(0, 0, 0));
        ButtonUpdate.setText("Update");
        ButtonUpdate.setBorder(null);
        ButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonUpdateMousePressed(evt);
            }
        });
        getContentPane().add(ButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 139, 48));

        tbAlamat.setBackground(new java.awt.Color(255, 255, 255));
        tbAlamat.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        tbAlamat.setForeground(new java.awt.Color(0, 0, 0));
        tbAlamat.setBorder(null);
        getContentPane().add(tbAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 770, 480, 39));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Karyawan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnBack1.setBackground(new java.awt.Color(24, 90, 102));
        btnBack1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Back(3).png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton4.setBackground(new java.awt.Color(24, 90, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/minimize(2).png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 30, 30));

        jButton5.setBackground(new java.awt.Color(24, 90, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Exit (3).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/HeaderHistory.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 50));

        btnAktif.setBackground(new java.awt.Color(204, 204, 204));
        btnAktif.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnAktif.setForeground(new java.awt.Color(0, 0, 0));
        btnAktif.setText("Acitivate");
        btnAktif.setBorder(null);
        btnAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktifActionPerformed(evt);
            }
        });
        getContentPane().add(btnAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 850, 139, 48));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Username");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, 42));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("No Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 820, -1, 42));

        tbUsername.setBackground(new java.awt.Color(255, 255, 255));
        tbUsername.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        tbUsername.setForeground(new java.awt.Color(0, 0, 0));
        tbUsername.setBorder(null);
        getContentPane().add(tbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 480, 39));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, -1, 42));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, 42));

        tbNama.setBackground(new java.awt.Color(255, 255, 255));
        tbNama.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 14)); // NOI18N
        tbNama.setForeground(new java.awt.Color(0, 0, 0));
        tbNama.setBorder(null);
        getContentPane().add(tbNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 480, 39));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Alamat");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, 42));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Jabatan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 880, -1, 30));

        TabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabelKaryawanMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TabelKaryawan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1130, -1));

        cmbPilih.setBackground(new java.awt.Color(187, 187, 187));
        cmbPilih.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        cmbPilih.setForeground(new java.awt.Color(0, 0, 0));
        cmbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Admin", "Kasir" }));
        getContentPane().add(cmbPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 880, 480, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/TextStokck.png"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 566, 800, 400));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/bgHistory.png"))); // NOI18N
        jLabel9.setText("jLabel4");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setDoubleBuffered(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        if (jabatan == 0) {
            formPilihManager f = new formPilihManager(jabatan);
            f.setVisible(true);
            this.dispose();
        }
        else{
            LoginForm f = new LoginForm();
            f.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(MasterKaryawan.ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TabelKaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKaryawanMousePressed
        //JOptionPane.showMessageDialog(rootPane, TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0).toString());
//tbID.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0).toString());
        tbNama.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 2).toString());
        tbUsername.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 1).toString());
        tbEmail.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 3).toString());
        tbAlamat.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 4).toString());
        tbNoTelp.setText(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 5).toString());
        if (TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 6).equals("Manager")) {
            cmbPilih.setSelectedIndex(0);
        }else if (TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 6).equals("Admin")) {
            cmbPilih.setSelectedIndex(1);
        }else if (TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 6).equals("Kasir")) {
            cmbPilih.setSelectedIndex(2);
        }
    }//GEN-LAST:event_TabelKaryawanMousePressed

    private void ButtonUpdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUpdateMousePressed
        // TODO add your handling code here:
        int kode = Integer.parseInt(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0).toString());
        try {
            // TODO add your handling code here:
            refreshTabel();

            pr = Proyek_PBO.conn.prepareStatement("UPDATE KARYAWAN SET NAMA= '"+tbNama.getText()+"' ,EMAIL='"+tbEmail.getText()+"',ALAMAT='"+tbAlamat.getText()+"',NOMORTELP='"+tbNoTelp.getText()+"', JABATAN= "+cmbPilih.getSelectedIndex()+" where IDKARYAWAN= "+kode+"");
            
            int rowUpdated = pr.executeUpdate();
            if (rowUpdated==1) {
                JOptionPane.showMessageDialog(rootPane, "Berhasil Update Karyawan");
                clear();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Gagal Update");
            }
            Tampil();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            //Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonUpdateMousePressed

    private void cmbJabatanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJabatanItemStateChanged
        // TODO add your handling code here:
        int ctr = cmbJabatan.getSelectedIndex();
        String j = cmbJabatan.getItemAt(ctr);
        if (j.equals("MANAGER")) {
            ctr = 0;
        }
        else if (j.equals("ADMIN")) {
            ctr = 1;
        }
        else if (j.equals("KASIR")) {
            ctr = 2;
        }
        if (j.equals("SEMUA")) {
            Tampil();
        }
        else
        {
            try {
                refreshTabel();
                st = Proyek_PBO.conn.createStatement();
                String sql = "select IDKARYAWAN,USERNAME,NAMA,EMAIL,ALAMAT,NOMORTELP,case when JABATAN = 0 Then 'Manager' when JABATAN = 1 then 'Admin' else 'Kasir' end as JABATAN, case when STATUS = 0 Then 'Tidak Aktif' when STATUS= 1 then 'Aktif' end as STATUS from karyawan where jabatan like '%"+ctr+"%' and lower(nama) like '%"+tbCari.getText()+"%'";
                rs = st.executeQuery(sql);
                while (rs.next()) {                
                    Object vdata = new Object[]{rs.getInt("IDKARYAWAN"),rs.getString("USERNAME"),rs.getString("NAMA"),rs.getString("EMAIL"),rs.getString("ALAMAT"),rs.getString("NOMORTELP"),rs.getString("Jabatan"),rs.getString("STATUS")};
                    model.addRow((Object[]) vdata);

    //                model.addRow(rows);
                }

                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_cmbJabatanItemStateChanged

    private void tbCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCariKeyTyped
        // TODO add your handling code here:
       int ctr = cmbJabatan.getSelectedIndex();
        String j = cmbJabatan.getItemAt(ctr);
        if (j.equals("MANAGER")) {
            ctr = 0;
        }
        else if (j.equals("ADMIN")) {
            ctr = 1;
        }
        else if (j.equals("KASIR")) {
            ctr = 2;
        }
        if (j.equals("SEMUA")) {
            try {
                refreshTabel();
                st = Proyek_PBO.conn.createStatement();
                String sql = "select IDKARYAWAN,USERNAME,NAMA,EMAIL,ALAMAT,NOMORTELP,case when JABATAN = 0 Then 'Manager' when JABATAN = 1 then 'Admin' else 'Kasir' end as JABATAN, case when STATUS = 0 Then 'Tidak Aktif' when STATUS= 1 then 'Aktif' end as STATUS from karyawan where lower(nama) like '%"+tbCari.getText()+"%'";
                rs = st.executeQuery(sql);
                while (rs.next()) {                
                    Object vdata = new Object[]{rs.getInt("IDKARYAWAN"),rs.getString("USERNAME"),rs.getString("NAMA"),rs.getString("EMAIL"),rs.getString("ALAMAT"),rs.getString("NOMORTELP"),rs.getString("Jabatan"),rs.getString("STATUS")};
                    model.addRow((Object[]) vdata);

    //                model.addRow(rows);
                }

                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                refreshTabel();
                st = Proyek_PBO.conn.createStatement();
                String sql = "select IDKARYAWAN,USERNAME,NAMA,EMAIL,ALAMAT,NOMORTELP,case when JABATAN = 0 Then 'Manager' when JABATAN = 1 then 'Admin' else 'Kasir' end as JABATAN, case when STATUS = 0 Then 'Tidak Aktif' when STATUS= 1 then 'Aktif' end as STATUS from karyawan where jabatan like '%"+ctr+"%' and lower(nama) like '%"+tbCari.getText()+"%'";
                rs = st.executeQuery(sql);
                while (rs.next()) {                
                    Object vdata = new Object[]{rs.getInt("IDKARYAWAN"),rs.getString("USERNAME"),rs.getString("NAMA"),rs.getString("EMAIL"),rs.getString("ALAMAT"),rs.getString("NOMORTELP"),rs.getString("Jabatan"),rs.getString("STATUS")};
                    model.addRow((Object[]) vdata);

    //                model.addRow(rows);
                }

                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_tbCariKeyTyped

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            refreshTabel();
            pr = Proyek_PBO.conn.prepareStatement("INSERT INTO KARYAWAN(USERNAME,PASSWORD,NAMA,EMAIL,ALAMAT,NOMORTELP,JABATAN,STATUS) VALUES(?,?,?,?,?,?,?,?)");
            pr.setString(1,tbUsername.getText());
            pr.setString(2,tbUsername.getText());
            pr.setString(3,tbNama.getText());
            pr.setString(4,tbEmail.getText());
            pr.setString(5,tbAlamat.getText());
            pr.setString(6,tbNoTelp.getText());
            pr.setInt(7,cmbPilih.getSelectedIndex());
            pr.setInt(8,1);
            
            int rowUpdated = pr.executeUpdate();
            if (rowUpdated==1) {
                JOptionPane.showMessageDialog(rootPane, "Berhasil Insert");
                clear();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Gagal Insert");
            }
            Tampil();
            clear();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            //Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void ButtonOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonOFFMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int kode = Integer.parseInt(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0).toString());
        //JOptionPane.showMessageDialog(rootPane, kode);
        try {
            // TODO add your handling code here:
            refreshTabel();
            
            pr = Proyek_PBO.conn.prepareStatement("UPDATE KARYAWAN SET STATUS= 0 where IDKARYAWAN= ?");
//            pr.setInt(2,CMBJabatan.getSelectedIndex());
//            String id=(String) TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0);
//                    System.out.println(id);
//            int ids=Integer.parseInt(id);
            pr.setInt(1,kode);
            int rowUpdated = pr.executeUpdate();
            if (rowUpdated==1) {
                JOptionPane.showMessageDialog(rootPane, "Berhasil Menonaktifkan Karyawan");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Gagal Update");
            }
            Tampil();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            //Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonOFFMouseClicked

    private void btnAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktifActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        int kode = Integer.parseInt(TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0).toString());
        //JOptionPane.showMessageDialog(rootPane, kode);
        try {
            // TODO add your handling code here:
            refreshTabel();
            
            pr = Proyek_PBO.conn.prepareStatement("UPDATE KARYAWAN SET STATUS= 1 where IDKARYAWAN= ?");
//            pr.setInt(2,CMBJabatan.getSelectedIndex());
//            String id=(String) TabelKaryawan.getValueAt(TabelKaryawan.getSelectedRow(), 0);
//                    System.out.println(id);
//            int ids=Integer.parseInt(id);
            pr.setInt(1,kode);
            int rowUpdated = pr.executeUpdate();
            if (rowUpdated==1) {
                JOptionPane.showMessageDialog(rootPane, "Berhasil Mengaktifkan Karyawan");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Gagal Update");
            }
            Tampil();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            //Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAktifActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    public void clear()
    {
        tbNama.setText("");
        tbUsername.setText("");
        tbEmail.setText("");
        tbAlamat.setText("");
        tbNoTelp.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonOFF;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTable TabelKaryawan;
    private javax.swing.JButton btnAktif;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JComboBox<String> cmbPilih;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField tbAlamat;
    private javax.swing.JTextField tbCari;
    private javax.swing.JTextField tbEmail;
    private javax.swing.JTextField tbNama;
    private javax.swing.JTextField tbNoTelp;
    private javax.swing.JTextField tbUsername;
    // End of variables declaration//GEN-END:variables

    private void Tampil() {
        try {
            refreshTabel();
            st = Proyek_PBO.conn.createStatement();
            String sql = "select IDKARYAWAN,USERNAME,NAMA,EMAIL,ALAMAT,NOMORTELP,case when JABATAN = 0 Then 'Manager' when JABATAN = 1 then 'Admin' else 'Kasir' end as JABATAN, case when STATUS = 0 Then 'Tidak Aktif' when STATUS= 1 then 'Aktif' end as STATUS from karyawan";
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object vdata = new Object[]{rs.getInt("IDKARYAWAN"),rs.getString("USERNAME"),rs.getString("NAMA"),rs.getString("EMAIL"),rs.getString("ALAMAT"),rs.getString("NOMORTELP"),rs.getString("Jabatan"),rs.getString("STATUS")};
                model.addRow((Object[]) vdata);
                
//                model.addRow(rows);
            }
            
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
//        for (int i = 0; i < TabelKaryawan.getRowCount(); i++) {
//            if (TabelKaryawan.getValueAt(i, 7).toString().equals("0")) {
//                TabelKaryawan.setForeground(Color.red);
//            }else if(TabelKaryawan.getValueAt(i, 7).toString().equals("1")){
//                            TabelKaryawan.setForeground(Color.BLUE);
//
//            } 
//        }
    }

    private void refreshTabel() {
         model = new DefaultTableModel(rows,0);
        TabelKaryawan.setModel(model);
    }
}
