/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javafx.beans.binding.Bindings;
import javax.swing.ImageIcon;

/**
 *
 * @author WIN10
 */
public class MasterKasir extends javax.swing.JFrame {

    /**
     * Creates new form MasterKasir
     */
    
    Object[] rows;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    PreparedStatement pr;
    int jabatan;
    ArrayList<Trans> arr = new ArrayList<>();
    
    Object[] rowsCart;
    DefaultTableModel modelCart;
    Statement stCart;
    ResultSet rsCart;
    PreparedStatement prCart;
    
    ResultSet rsCount;
    PreparedStatement prCount;    
    
    Statement stTrans;
    ResultSet rsTrans;
    PreparedStatement psTrans;
    

    public MasterKasir(int jabatan) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        this.jabatan = jabatan;
        System.out.println(jabatan);
        if (jabatan == 0 || jabatan == 1) {
            btnCheckout.setVisible(false);
            btnRemove.setVisible(false);
            btnRemoveAll.setVisible(false);
        }
       
        tblStok.setDefaultEditor(Object.class, null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        rows = new Object[]{"ID","Nama Barang","Harga Normal","Jenis","Stok","Harga Grosir"};
        model = new DefaultTableModel(rows,0);
        tblStok.setModel(model);
        tampil();
        tblStok.getTableHeader().setReorderingAllowed(false);
        
        tblCart.setDefaultEditor(Object.class, null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        rowsCart = new Object[]{"Nama Barang","Harga","Quantity","Subtotal"};
        modelCart = new DefaultTableModel(rowsCart,0);
        tblCart.setModel(modelCart);
        tblStok.getTableHeader().setReorderingAllowed(false);
        modelCart = new DefaultTableModel(rowsCart,0);
        tblCart.setModel(modelCart);
    }

    private MasterKasir() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void tampil()
    {
        
        try {
            refreshTabel();
            st = Proyek_PBO.conn.createStatement();
            String sql = "select b.IDBARANG,b.NAMABARANG,b.HARGANORMAL,j.NAMAJENIS, b.STOK, b.HARGAGROSIR from barang b, jenisbarang j where b.fk_jenis = j.idjenis and b.stok > 0";
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object vdata = new Object[]{rs.getInt("IDBARANG"),rs.getString("NAMABARANG"),rs.getInt("HARGANORMAL"),rs.getString("NAMAJENIS"),rs.getInt("STOK"),rs.getInt("HARGAGROSIR")};
                model.addRow((Object[]) vdata);
            }
            
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void refreshTabel()
    {
        model = new DefaultTableModel(rows,0);
        tblStok.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStok = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        labelSelectedBarang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("Aktifkan");

        jButton2.setText("Update");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblStokMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblStok);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 130, 1150, 400));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCartMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblCart);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 750, 360));
        getContentPane().add(labelSelectedBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 200, 200));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 750, -1, -1));

        lbTotal.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal.setText("0");
        getContentPane().add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 750, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 50));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 19)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 300, 30));

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/searchBlc(1).png"))); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 30, 30));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cart");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        btnCheckout.setBackground(new java.awt.Color(204, 204, 204));
        btnCheckout.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(0, 0, 0));
        btnCheckout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/checkout(2).png"))); // NOI18N
        btnCheckout.setText("Check Out");
        btnCheckout.setBorder(null);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 899, 371, 50));

        btnRemove.setBackground(new java.awt.Color(204, 204, 204));
        btnRemove.setForeground(new java.awt.Color(0, 0, 0));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/trash-bin(3).png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setBorder(null);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 830, 166, 50));

        btnRemoveAll.setBackground(new java.awt.Color(204, 204, 204));
        btnRemoveAll.setForeground(new java.awt.Color(0, 0, 0));
        btnRemoveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/trash-bin (2).png"))); // NOI18N
        btnRemoveAll.setText("Remove All");
        btnRemoveAll.setBorder(null);
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 830, 166, 50));

        btnBack1.setBackground(new java.awt.Color(24, 90, 102));
        btnBack1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Back(3).png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(24, 90, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/minimize(2).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 30, 30));

        jButton4.setBackground(new java.awt.Color(24, 90, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Exit (3).png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/HeaderHistory.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/bgHistory.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setDoubleBuffered(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1190, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        if (jabatan == 2) {
            formPilihKasir f = new formPilihKasir(jabatan);
            f.setVisible(true);
            this.dispose();
        }else{
            LoginForm f = new LoginForm();
            f.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(MasterKasir.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblStokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStokMousePressed
        // TODO add your handling code here:
        int idx = tblStok.getSelectedRow();
        String kode = model.getValueAt(idx, 0).toString();
        ImageIcon iconproduk = new ImageIcon("Gambar_Produk/"+kode+".jpg");
        //ImageIcon iconproduk = new ImageIcon(getClass().getResource(("/proyek_pbo/Gambar_Produk/"+kode+".jpg")));
        Image gambarproduk = iconproduk.getImage();
        Image scaleproduk = gambarproduk.getScaledInstance(labelSelectedBarang.getWidth(), labelSelectedBarang.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon produkscaled = new ImageIcon(scaleproduk);
        labelSelectedBarang.setIcon(produkscaled);
        
        String jumlah = JOptionPane.showInputDialog("Masukkan jumlah yang akan dibeli : ");
        //JOptionPane.showMessageDialog(rootPane, jumlah);
        
        if (jumlah!=null) {
            int jml = Integer.parseInt(jumlah);
            int stok = Integer.parseInt(tblStok.getValueAt(idx, 4).toString());
            if (jml <= stok) {
                int harga = 0;
                if (jml<=5) {
                    harga = Integer.parseInt(model.getValueAt(idx, 2).toString());
                }
                else {
                    harga = Integer.parseInt(model.getValueAt(idx, 5).toString());
                }
                String nama = model.getValueAt(idx, 1).toString();
                int ID = Integer.parseInt(model.getValueAt(idx, 0).toString());
                int subtotal = jml * harga;
                Trans t = new Trans(nama,harga,jml,subtotal,ID);
                arr.add(t);
                refresh();
                refreshTotal();
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Stok tidak mencukupi, silahkan ulangi");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Jumlah belum terisi, gagal menambahkan barang dalam keranjang");
        }
    }//GEN-LAST:event_tblStokMousePressed

    public void refreshTotal()
    {
        int total = 0;
        for (int i = 0; i < arr.size(); i++) {
            total += arr.get(i).getSubtotal();
        }
        lbTotal.setText(total+"");
    }
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int pos = tblCart.getSelectedRow();
        if (pos!=-1) {
            arr.remove(pos);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Pilih item dalam cart yang akan dihapus, gagal hapus");
        }
        //arr.remove(pos);
        refresh();
        refreshTotal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        // TODO add your handling code here:
        arr.clear();
        refresh();
        refreshTotal();
    }//GEN-LAST:event_btnRemoveAllActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        String voucher = JOptionPane.showInputDialog("Masukkan Kode Voucher : ");
        if (voucher!=null) {
            int tipe=-1;
        try {
            String sql = "select tipepotongan from voucher where idvoucher like ?";
            prCount = Proyek_PBO.conn.prepareStatement(sql);
            prCount.setString(1,"%"+voucher+"%");
            rsCount = prCount.executeQuery();
            if (rsCount.next() ) {  
              tipe = rsCount.getInt(1);  
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(Global.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double potongan = -1;
        
        try {
            String sql = "select jumlah from voucher where idvoucher like ?";
            prCount = Proyek_PBO.conn.prepareStatement(sql);
            prCount.setString(1,"%"+voucher+"%");
            rsCount = prCount.executeQuery();
            if (rsCount.next() ) {  
              potongan = rsCount.getInt(1);  
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(Global.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        double pot = potongan/100;
        
        if (tipe==0) {
            potongan = pot * Integer.parseInt(lbTotal.getText());
        }
        
        double general = Integer.parseInt(lbTotal.getText());
        general = general - potongan;
        
        
        lbTotal.setText((int)(general)+"");
        
        DateFormat formatTanggal = new SimpleDateFormat("dd/MM/yyyy");
	Date tanggal = new Date();
	//JOptionPane.showMessageDialog(rootPane,formatTanggal.format(tanggal));
        String tgl = formatTanggal.format(tanggal);
        String nota = generateNoNota();
        try {
            Proyek_PBO.conn.setAutoCommit(false);
            
            String sql = "insert into htrans(nomornota, tanggalnota,grandtotal,fk_voucher) values(?,?,?,?)";
            psTrans = Proyek_PBO.conn.prepareStatement(sql);
            psTrans.setString(1, nota);
            psTrans.setString(2, tgl);
            psTrans.setInt(3, Integer.parseInt(lbTotal.getText()));
            psTrans.setInt(4, Integer.parseInt(voucher));
            psTrans.executeUpdate();
            
            for (int i = 0; i < arr.size(); i++) {
                psTrans = Proyek_PBO.conn.prepareStatement("insert into dtrans(h_nomornota,fk_barang,qty,subtotal,harga) values(?,?,?,?,?)");
                psTrans.setString(1, nota);
                psTrans.setInt(2, arr.get(i).getIDBarang());
                psTrans.setInt(3, arr.get(i).getQuantity());
                psTrans.setInt(4, arr.get(i).getSubtotal());
                psTrans.setInt(5, arr.get(i).getHarga());
                psTrans.executeUpdate();
            }
            
            Proyek_PBO.conn.commit();
            JOptionPane.showMessageDialog(rootPane, "Berhasil Memasukkan transaksi");
            for (int i = 0; i < arr.size(); i++) {
                try {
                    sql = "select stok from barang where idBarang like ?";
                    prCount = Proyek_PBO.conn.prepareStatement(sql);
                    prCount.setString(1,"%"+arr.get(i).getIDBarang()+"%");
                    rsCount = prCount.executeQuery();
                    if (rsCount.next() ) {  
                      int stok = rsCount.getInt(1);  
                      stok = stok - arr.get(i).getQuantity();
                      try {
                        // TODO add your handling code here:
                        refreshTabel();

                        pr = Proyek_PBO.conn.prepareStatement("UPDATE BARANG SET stok = "+stok+" where IDBARANG = "+arr.get(i).getIDBarang()+"");
                        int rowUpdated = pr.executeUpdate();
                        if (rowUpdated==1) {
                            JOptionPane.showMessageDialog(rootPane, "Berhasil Update Stok");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Gagal Update");
                        }
                        tampil();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                        //Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    }

                } catch (SQLException ex) {
                    //Logger.getLogger(Global.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            arr.clear();
            refresh();
            lbTotal.setText("0");
            
        } catch (Exception ex) {
            try {
                Proyek_PBO.conn.rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(MasterKasir.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(MasterKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Voucher belum diinputkan, silahkan masukkan 0 sebagai transaksi normal");
        }
        
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        try {
                refreshTabel();
                pr = Proyek_PBO.conn.prepareStatement("select b.IDBARANG,b.NAMABARANG,b.HARGANORMAL,j.NAMAJENIS, b.STOK, b.HARGAGROSIR from barang b, jenisbarang j where b.fk_jenis = j.idjenis and lower(b.namabarang) like ? and b.stok > 0 order by b.harganormal asc");
                //pr.setString(1,"%"+kat+"%");
                pr.setString(1,"%"+jTextField1.getText()+"%");
                rs = pr.executeQuery();
                while (rs.next()) {                
                    Object vdata = new Object[]{rs.getInt("IDBARANG"),rs.getString("NAMABARANG"),rs.getInt("HARGANORMAL"),rs.getString("NAMAJENIS"),rs.getInt("STOK"),rs.getInt("HARGAGROSIR")};
                    model.addRow((Object[]) vdata);
                }
                rs.close();

                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void tblCartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMousePressed
        labelSelectedBarang.setIcon(null);
    }//GEN-LAST:event_tblCartMousePressed

    public String generateNoNota()
    {
        DateFormat formatTanggal = new SimpleDateFormat("dd/MM/yyyy");
	Date tanggal = new Date();
	//JOptionPane.showMessageDialog(rootPane,formatTanggal.format(tanggal));
        String tgl = formatTanggal.format(tanggal);
        String[] format = tgl.split("/");
        String nota = format[2] + format[1] + format[0];
        int sequence=0;
        try {
            String sql = "select count(*) from htrans where nomornota like ?";
            prCount = Proyek_PBO.conn.prepareStatement(sql);
            prCount.setString(1,"%"+nota+"%");
            rsCount = prCount.executeQuery();
            if (rsCount.next() ) {  
              sequence = rsCount.getInt(1);  
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(Global.class.getName()).log(Level.SEVERE, null, ex);
        }
        sequence = sequence + 1;
        String urut = (sequence +"").format("%03d", sequence);
        nota = nota + urut;
        return nota;
    }
    
    public void refresh()
    {
        modelCart = new DefaultTableModel(rowsCart,0);
        tblCart.setModel(modelCart);
        for (int i = 0; i < arr.size(); i++) {
            Object vdataCart = new Object[]{arr.get(i).getNama(),arr.get(i).getHarga(),arr.get(i).getQuantity(),arr.get(i).getSubtotal()};
            modelCart.addRow((Object[]) vdataCart);

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelSelectedBarang;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblStok;
    // End of variables declaration//GEN-END:variables
}
