/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek_pbo;

import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class Voucher extends javax.swing.JFrame {

    /**
     * Creates new form Voucher
     */
    
    int jabatan;
    Object[] rows;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    PreparedStatement pr;
    
    public Voucher(int jabatan) {
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        this.jabatan = jabatan;
        tbVoucher.setDefaultEditor(Object.class, null);
        rows = new Object[]{"ID Voucher","Nama Voucher","Tipe"};
        model = new DefaultTableModel(rows,0);
        tbVoucher.setModel(model);
        Tampil();
        tbVoucher.getTableHeader().setReorderingAllowed(false);
    }

    private Voucher() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelVoucher = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVoucher = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(24, 90, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/minimize(2).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        btnBack1.setBackground(new java.awt.Color(24, 90, 102));
        btnBack1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 12)); // NOI18N
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Back(3).png"))); // NOI18N
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(24, 90, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Exit (3).png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu Voucher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 60));
        getContentPane().add(labelVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 570, 230));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Header.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/TextStokck.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 790, 340));

        tbVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbVoucherMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbVoucher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 790, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyek_pbo/Bg.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setDoubleBuffered(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(Voucher.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbVoucherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVoucherMousePressed
        // TODO add your handling code here:
        int idx = tbVoucher.getSelectedRow();
        String kode = model.getValueAt(idx, 0).toString();
        
        ImageIcon iconproduk = new ImageIcon("Gambar_Produk/Voucher/"+kode+".png");
        //ImageIcon iconproduk = new ImageIcon(getClass().getResource(("/proyek_pbo/Gambar_Produk/"+kode+".jpg")));
        Image gambarproduk = iconproduk.getImage();
        Image scaleproduk = gambarproduk.getScaledInstance(labelVoucher.getWidth(), labelVoucher.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon produkscaled = new ImageIcon(scaleproduk);
        labelVoucher.setIcon(produkscaled);
    }//GEN-LAST:event_tbVoucherMousePressed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        if (jabatan == 0) {
            formPilihManager f = new formPilihManager(jabatan);
            f.setVisible(true);
            this.dispose();
        }else if (jabatan == 2) {
            formPilihKasir f = new formPilihKasir(jabatan);
            f.setVisible(true);
            this.dispose();
        }
        else{
            LoginForm f = new LoginForm();
            f.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnBack1ActionPerformed

    private void refreshTabel() {
        model = new DefaultTableModel(rows,0);
        tbVoucher.setModel(model);
    }
    
     private void Tampil() {
        try {
            refreshTabel();
            st = Proyek_PBO.conn.createStatement();
            String sql = "SELECT IDVOUCHER,namavoucher, CASE WHEN JUMLAH>=100 THEN CONCAT(\"Rp. \",JUMLAH) ELSE CONCAT(JUMLAH,\"%\") end AS POTONGAN FROM voucher where idvoucher>0";
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object vdata = new Object[]{rs.getInt("IDVoucher"),rs.getString("namavoucher"),rs.getString("potongan")};
                model.addRow((Object[]) vdata);
                
//                model.addRow(rows);
            }
            
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(MasterStok.class.getName()).log(Level.SEVERE, null, ex);
        }
//        for (int i = 0; i < TabelKaryawan.getRowCount(); i++) {
//            if (TabelKaryawan.getValueAt(i, 7).toString().equals("0")) {
//                TabelKaryawan.setForeground(Color.red);
//            }else if(TabelKaryawan.getValueAt(i, 7).toString().equals("1")){
//                            TabelKaryawan.setForeground(Color.BLUE);
//
//            } 
//        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVoucher;
    private javax.swing.JTable tbVoucher;
    // End of variables declaration//GEN-END:variables
}
